issuesOpened: >
  Thank you for reporting a Perigee issue.<br /><br />
  The Perigee issue tracker is for reproducible bugs and specific feature requests.
  For a bug, complete the bug report template and include the requested logs.<br /><br />
  Thank you for helping improve Perigee.
