#pragma once

// App-owned SDL_USEREVENT codes. Keep these in one place because SDL2 and
// sdl2-compat both share the same SDL_UserEvent::code namespace.
#define SDL_CODE_FRAME_READY 0
#define SDL_CODE_FLUSH_WINDOW_EVENT_BARRIER 100
#define SDL_CODE_GAMECONTROLLER_RUMBLE 101
#define SDL_CODE_GAMECONTROLLER_RUMBLE_TRIGGERS 102
#define SDL_CODE_GAMECONTROLLER_SET_MOTION_EVENT_STATE 103
#define SDL_CODE_GAMECONTROLLER_SET_CONTROLLER_LED 104
#define SDL_CODE_GAMECONTROLLER_SET_ADAPTIVE_TRIGGERS 105
#define SDL_CODE_INPUT_TIMER 106
#define SDL_CODE_PERIGEE_FIRST_FRAME 107
